### ISSUE TITLE
Implement Process 2023

### ISSUE THREAD

**Issue by koalie** [w3c/modern-tooling#106]
- [x] [Draft announcement: AC comment period](https://github.com/w3c/AB-memberonly/blob/master/documents/drafts/2023-04/process-announcement.txt) (Florian & fantasai)
- [x] [Draft Design Considerations FAQ](https://github.com/w3c/AB-memberonly/blob/master/documents/drafts/2023-04/process-faq.md) (Florian & fantasai)
- [x] Process 2023 in place (@plehegar)
- [x] Send announcement to Members/Chairs/AB/TAG (@koalie or @xueyuanjia)
- [x] Forward announcement to public-w3process@w3.org (@koalie or @xueyuanjia)
- [x] Post homepage news + other promotion (@koalie or @xueyuanjia)
- [x] supersede Process 2021 (@plehegar)
- [x] update Process/.htaccess (@swickr)
- [x] check if any update is needed to https://www.w3.org/standards/types (@plehegar) 
- [x] Transition requirements (@plehegar)
- [x] Pubrules (@deniak or @jennyliang220)
- [x] any change to reflect on IPP pages (new Process)? (@deniak) 
- [x] Update Call for Exclusions emails in IPP (@deniak)
- [x] WBS AC forms update (@koalie or @xueyuanjia)
- [x] any change to reflect for Echidna support? (@deniak) 
- [x] any change to reflect for publication database and /TR history pages update? (@@)
- [x] any change to reflect on the [spec templates](https://github.com/w3c/tr-design/tree/gh-pages/p2021mockup) (@plehegar ) https://w3c.github.io/tr-design/p2021mockup/
- [x] any change to reflect for Bikeshed? (@deniak)
- [x] any change to reflect for ReSpec? (@deniak)
- [x] Update [team mail templates](https://www.w3.org/Team/Templates/) (@koalie or @xueyuanjia)
- [x] any change to reflect to the [guidebook](https://www.w3.org/Guide/) or the [charter guidebook](https://www.w3.org/Guide/process/charter.html)? (@plehegar)
- [x] Create [Council Reports page](https://www.w3.org/about/council/) (@koalie or @plehegar)
- [x] any change to reflect on the [Charter template](https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html) ?  (@plehegar)
- [ ] which partner orgs need to be contacted about the updates (@@) 

(NOTE: this is an ongoing process in preparation of the Process 2023 deployment)

**Comment by plehegar** [comment]
Timeline:
- end of AC review: May 24

**Comment by deniak** [comment]
@plehegar now that the new process is in effect, I'll start working on updating the publication tools.
Do we plan a transition period and if so, how long should it last?
AFAIK, there's not much to update on this side but it would be good to schedule a call to discuss these details.

**Comment by plehegar** [comment]
@deniak we did not plan a transition period but I'm limited in my actions while on the road so not much of a choice, we can't stop publications. I believe we only need to replace the dated links to the Process document in the SOTD.

**Comment by xueyuanjia** [comment]
Hi @koalie I've updated the [team mail templates](https://www.w3.org/Team/Templates/), referring to Process 2023 and updating the signature block.

**Comment by deniak** [comment]
I'm expecting to work on this next week so hopefully the publications tools will start accepting the new process before the end of the month.

**Comment by deniak** [comment]
@plehegar I've prepared a [PR for specberus to handle the new process](https://github.com/w3c/specberus/pull/1752) and I'll update echidna as well. AFAIK, only the link to the process is changing and the rest stays the same.
Since we will not have a transition period, we need to find a date to deploy this and update bikeshed/respec at the same time to avoid disruption. I can submit PRs for this once we have a date.

**Comment by deniak** [comment]
PR for [bikeshed](https://github.com/speced/bikeshed-boilerplate/pull/46) and [respec](https://github.com/w3c/respec/pull/4473) have been submitted for review.

After discussing with @plehegar, we are planning to merge these PRs and update all the publication tools on July 17.
This should be transparent for the editors as long as they use the latest version of bikeshed/respec

**Comment by deniak** [comment]
PRs for the various publication tools and backend have been merged and deployed!

**Comment by plehegar** [comment]
Transition update: https://github.com/w3c/transitions/commit/00baebe1490df49e73be5f94741d26d776aefe40

**Comment by plehegar** [comment]
All done
