### ISSUE TITLE
Closer integration with specifiction?

### ISSUE THREAD

**Issue by jonathanKingston** [w3c/modern-tooling#11]
As discourse.specifiction.org was mentioned on the W3C blog, I assume it is basically W3C endorsed.

Is it worth mentioning in this discussion, or is there wider plans for user interaction?

I know Github have issues but I get the feeling using a more user friendly forum would promote more interaction of ideas outside of the usual contributors.

**Comment by darobin** [comment]
Our Discourse setup is not yet W3C endorsed (it was created as a personal experiment), but it is going to be. Basically it is a matter of transferring it to a W3C-operated domain (with a name that people remember and can spell easily), of rebranding it a bit, and of making sure the contribution rules are all okay. This is all under way already!

But yes, I do plan to mention this in the report. Thanks!

**Comment by jonathanKingston** [comment]
@darobin :+1: thanks for the clarification, better adoption certainly would help with the official stamp. I only discovered it by having W3C news in my feeds.

Thanks for moving this forward with all your mentioned actions. As a personal experiment it has done pretty well to say how many active members there are.
