### ISSUE TITLE
Implement Process 2023.1

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#111]
- [x] Process 2023.1 in place (@plehegar)
- [x] Send announcement to Members/Chairs/AB/TAG (@xueyuanjia)
- [x] Forward announcement to public-w3process@w3.org (@xueyuanjia)
- [x] Post homepage news (@xueyuan)
- [x] other promotions (@koalie @amyvdh @xueyuanjia)
- [x] supersede Process 2023 (@plehegar)
- [x] update Process/.htaccess (@plehegar)
- [x] check if any update is needed to https://www.w3.org/standards/types (@plehegar) 
- [x] Transition requirements (@plehegar)
- [x] Pubrules (@deniak)
- [x] any change to reflect on IPP pages (new Process)? (@deniak) 
- [x] Update Call for Exclusions emails in IPP (@deniak)
- [x] WBS AC forms update (@xueyuanjia)
- [x] any change to reflect for Echidna support? (@deniak) 
- [x] any change to reflect for publication database and /TR history pages update? (@deniak)
- [x] any change to reflect for Bikeshed? (@deniak)
- [x] any change to reflect for ReSpec? (@deniak)
- [x] Update [team mail templates](https://www.w3.org/Team/Templates/) (@xueyuanjia)
- [x] any change to reflect to the [guidebook](https://www.w3.org/Guide/) or the [charter guidebook](https://www.w3.org/Guide/process/charter.html)? (@plehegar)
- [x] any change to reflect on the [Charter template](https://github.com/w3c/charter-drafts/blob/gh-pages/charter-template.html) ?  (@plehegar)

(NOTE: this is an ongoing process in preparation of the Process 2023.1 deployment)

**Comment by plehegar** [comment]
@deniak , we can easily grant a grace period on TR publications since none of Process 2023.1 affects /TR. The only thing that comes to mind is avoid to place a deadline close to a publication moratorium since folks will be in a rush to publish at the last minute. How about until December 3?

**Comment by xueyuanjia** [comment]
The Process URI in the WBS AC forms uses [https://www.w3.org/Consortium/Process/](https://www.w3.org/Consortium/Process/). To have the forms updated, can you please direct [https://www.w3.org/Consortium/Process/](https://www.w3.org/Consortium/Process/) to [https://www.w3.org/2023/Process-20231103/](https://www.w3.org/2023/Process-20231103/) as the "Latest published version"? @plehegar

**Comment by deniak** [comment]
> @deniak , we can easily grant a grace period on TR publications since none of Process 2023.1 affects /TR. The only thing that comes to mind is avoid to place a deadline close to a publication moratorium since folks will be in a rush to publish at the last minute. How about until December 3?

Sounds good to me. I'll update the publication toolchain to start accepting the new process on Monday.

**Comment by xueyuanjia** [comment]
Hi @koalie @amyvdh Do you think we should make any other promotion for the Updated 2023 Process Document? I've sent announcements to [Members (AC,AB, TAG, Chairs)](https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0026.html) and [Process CG's public mailing list](https://lists.w3.org/Archives/Public/public-w3process/2023Nov/0000.html), and posted [a news item on W3C homepage](https://www.w3.org/news/2023/w3c-updates-its-2023-process-document/).

**Comment by deniak** [comment]
@plehegar @koalie, do we refer to that version of the process document with "Process Document 2023.1" ?

**Comment by plehegar** [comment]
@deniak ,for the purpose of /TR, we can refer to it as Process 2023. The distinction between the two doesn't matter.

**Comment by deniak** [comment]
Pubrules, echidna and the backend have been updated to accept the new process doc.
We will keep accepting the previous process until December 3 included.

**Comment by deniak** [comment]
PRs for respec and bikeshed have been submitted:
* https://github.com/w3c/respec/pull/4573
* https://github.com/speced/bikeshed-boilerplate/pull/52

**Comment by koalie** [comment]
> Hi @koalie @amyvdh Do you think we should make any other promotion for the Updated 2023 Process Document? I've sent announcements to [Members (AC,AB, TAG, Chairs)](https://lists.w3.org/Archives/Member/w3c-ac-members/2023OctDec/0026.html) and [Process CG's public mailing list](https://lists.w3.org/Archives/Public/public-w3process/2023Nov/0000.html), and posted [a news item on W3C homepage](https://www.w3.org/news/2023/w3c-updates-its-2023-process-document/).

No, I don't think it's necessary. Thanks, @xueyuanjia !

**Comment by plehegar** [comment]
I believe we're all done here. Closing.
