### ISSUE TITLE
Training for new tools

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#12]
The plan also needs to take into account training. It's fine and nice to switch to github but we shouldn't expect everyone to know github or learn from scratch by themselves. So, for github, we should put together a short "editor's intro to github" document and present that during a TPAC breakout.

**Comment by plehegar** [comment]
Same is true for the new automatic publishing system btw.

**Comment by darobin** [comment]
I've now included mention of documentation and training, thanks!
