### ISSUE TITLE
Adding a Translation Tool

### ISSUE THREAD

**Issue by StefanSTS** [w3c/modern-tooling#15]
Dear All,

I was wondering if git is a good place to add a translation tool too. 
With the source of the specs available, the translation could be done in the source and recurring parts like the copyright, the patent section and all this legal stuff could be just added with a snippet if it is already available in the specific language. So the final translation could be generated easily and also started long before the spec is actually in REC status, what would make it eventually available in different languages right from the day of the advance to REC.
The main issue will be to make it friendly for translators who might be not so techie. The process would need an easy to understand documentation and best a tool like these many fine tools like openhtml, jsfiddle or codepen and so on, where you can type in the source on one side and see your final result on the other.

Well, I am aware this is not a priority task, but if there is any margin left ... 

So short
Stefan

**Comment by darobin** [comment]
I've included a short section on translator tools. I don't think that it will be a high priority, but it is certainly an interesting area and we should strive to support the translating community. Thanks!

**Comment by StefanSTS** [comment]
Thanks Robin for adding the section. I am not the coder type, but if anyone is ever going to work on a tool, I would be happy to share my view how the interface might look like. Thanks again.
