### ISSUE TITLE
Integration of github issues with IRC

### ISSUE THREAD

**Issue by azaroth42** [w3c/modern-tooling#2]
Having issues in github (as per this one!) makes many tasks much easier than the aging W3C issue tracker.  The IRC integration for creating issues should be configurable to either create an issue in the tracker or in github, per WG.

**Comment by plehegar** [comment]
See also #16

**Comment by darobin** [comment]
This is now listed in the document, as part of http://w3c.github.io/modern-tooling/#issue-trackers. Thanks!
