### ISSUE TITLE
Spec-based, context-sensitive issue creation

### ISSUE THREAD

**Issue by r12a** [w3c/modern-tooling#26]
This may be too detailed for inclusion in the Modern Tooling doc, but maybe it's appropriate as an issue to capture the idea?

it would be wonderful if you could raise issues for github, tracker, bugzilla (whatever is appropriate) right from the actual spec.  This would automatically place a pointer in the comment to the document location that the comment refers to.  Ideally you'd also be able to highlight some text and have that inserted in blockquote style at the start of the comment, if you want to.

of course, this overlaps somewhat with spec annotation too.

**Comment by darobin** [comment]
That's already accounted for under #interactivity-in-specifications :)
