### ISSUE TITLE
Dependency tracker

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/modern-tooling#29]
Specs depends on one another, but there is very little made to ensure these dependencies are kept in sync; they are expected to be reviewed at transitions, and sometimes the link checker will spot a dependency gone wrong, but a more systematic approach would allow for better coordination across groups and reduce the risks for "monkey patching".

A dependency tracker that would allow to visualize and report the dependencies between spec, e.g. in terms of WebIDL interfaces, but also in terms of algorithms would be terrific. Ideally, they would lead to much more granular dependencies — a spec usually depends on a few items of a given spec, not the whole thing; assessing dependencies at the right granularity would be helpful for streamlining transitions on the Rec track.

**Comment by darobin** [comment]
I've added this. Note that when you have a well-defined idea like this, you can just make a PR ;)

**Comment by dontcallmedom** [comment]
I had been planning to make PR for 3 weeks now; I figured I should file issues quickly before I let 3 more weeks pass :)
