### ISSUE TITLE
What is the role of a WG's home page?

### ISSUE THREAD

**Issue by iherman** [w3c/modern-tooling#47]
Before going into the detail on what the WG homepage is a more fundamental question should be answered. Namely
- Is the home page a "working" page for the group? This is typically the case when a homepage is the group's, say, wiki page, linking to minutes, editor's drafts, names of the chairs, etc.
- It is the "outreach" page of the group, primarily used as a landing page for raising interest in the work, have a higher level message on what should be achieved by the group, usable for recruiting, etc.

These two functions are different, and both of them are needed. Having some uniform approach on this at W3C would be necessary.

**Comment by tripu** [comment]
The [current prototype for group pages](https://w3c.github.io/Unitas/?g=68239) in [Unitas](https://github.com/w3c/Unitas) (dashboards / dynamic pages project) aspires to provide both things: static information about the group, plus up-to-date details: specs published, charters, participants, chairs, team contacts, etc.

See also [all the proposals about new feeds, communication channels and sources of data](https://github.com/w3c/Unitas/issues?q=is%3Aissue+is%3Aopen+label%3Afeed) about groups.

**Comment by tripu** [comment]
@iherman, let's move the discussion to [Unitas issues](https://github.com/w3c/Unitas/issues), where we can steer the project in the best direction.
