### ISSUE TITLE
CSS Validator

### ISSUE THREAD

**Issue by cvrebert** [w3c/modern-tooling#49]
> 3.4.3 CSS & HTML Validators
> These are solid tools and do not need much work.

Am I missing something? The last commit in https://github.com/w3c/css-validator is from over 1.5 years ago, ~~and in my admittedly limited testing, http://www.css-validator.org seemed to choke on `transition`, `animation`, and `transform` properties, `rgba()` color values, and responsive media queries~~.
The project also suffers from a lack of documentation on how to run a local instance of the CSS validator.

**Comment by ylafon** [comment]
css-validator.org are probably using an outdated version (they are not affiliated with W3C). The latest sources are not on gh (a bug that should be fixed at some point), calc() is missing, but transition/animation/transform/rgba() and mq are in it.

**Comment by cvrebert** [comment]
> css-validator.org are probably using an outdated version (they are not affiliated with W3C)

That is very unfortunate (and confusing given that site's branding and copyright notice).
Okay, I re-checked using https://jigsaw.w3.org/css-validator/ , and that indeed seems reasonably up-to-date. So that just leaves the docs and source control issues.

> The latest sources are not on gh (a bug that should be fixed at some point)

How glacial of a timescale should I brace myself for?

**Comment by sideshowbarker** [comment]
> > css-validator.org are probably using an outdated version (they are not affiliated with W3C)
> 
> That is very unfortunate (and confusing given that site's branding and copyright notice).

I had never heard of http://www.css-validator.org/ before seeing it mentioned here. I have no idea who runs it but yeah they shouldn't be using W3C branding there and should at least be trying keep it up to date with the latest sources.

**Comment by sideshowbarker** [comment]
> > The latest sources are not on gh (a bug that should be fixed at some point)
> 
> How glacial of a timescale should I brace myself for?

I would say a matter of a few weeks (not months). I say this not knowing myself what version control system we're using for the sources (I looked in both https://dvcs.w3.org/hg and http://dev.w3.org/cvsweb/ and didn't find anything) but regardless I'd think it wouldn't be a huge amount of work to migrate them from wherever they are now to the github W3C space.

**Comment by cvrebert** [comment]
> I say this not knowing myself what version control system we're using for the sources

Presumably it's http://dev.w3.org/cvsweb/2002/css-validator/ based on the site's Download page.

**Comment by betehess** [comment]
I am still wondering why W3C is not making https://github.com/w3c/css-validator the official repository for the code.

I would be happy to re-initiate the work I did a while ago, including the CVS-to-git migration and the build to create the artifacts, including the standalone server. But **only** if W3C decides to continue the work on that repo.

**Comment by darobin** [comment]
Who gets to decide that? This is a great idea and we have a volunteer to do the work. What's not to like?

**Comment by betehess** [comment]
> Who gets to decide that?

I think it's a political choice at this point :-)

> What's not to like?

That it's been done before but we failed to continue the work on github.

**Comment by darobin** [comment]
Heh. I don't mind if it's political, my question is who I need to lobby :)

**Comment by tabatkins** [comment]
"Political choice" implies there's someone who still likes CVS. Who is that person, and where's the time machine they obviously just stepped out of from the year 2000?

**Comment by sideshowbarker** [comment]
The snark and speculation about "political choice" aren't really helpful. We're all friends here. So let's please treating each other like friends.

Everybody who's posted comments to this issue has expressed agreement on moving the repo to github. So let's not create some phantom argument here that doesn't exist.

We'll get the repo migratedー probably by taking up @betehess up on his offer but regardless by doing it in the same way we've previously migrated gobs of other repos to github without any acrimony.

**Comment by cvrebert** [comment]
So, as a first step, could we perhaps get a W3Cer to add to http://dev.w3.org/cvsweb/2002/css-validator/ a pointer to this GitHub repo?

**Comment by sideshowbarker** [comment]
> So, as a first step, could we perhaps get a W3Cer to add to http://dev.w3.org/cvsweb/2002/css-validator/ a pointer to this GitHub repo?

Done

**Comment by sideshowbarker** [comment]
So actually, since we already migrated the CSS Checker (aka Validator) sources to https://github.com/w3c/css-validator we can now close this issue. Reopen if I’m missing something.

**Comment by sideshowbarker** [comment]
hmm, um, we migrated them somewhere (now looking)

**Comment by sideshowbarker** [comment]
I’m confused. I thought we had already migrated the **current** sources to a github repo since after the time this issue was first raised. But I guess not?

**Comment by cvrebert** [comment]
https://github.com/w3c/css-validator already existed when I opened this issue.
https://github.com/w3c/css-validator doesn't now have any more commits than it did when I first opened this issue. Its latest commit still dates to Aug 9, 2013. Whereas http://dev.w3.org/cvsweb/2002/css-validator/ has commits dating to only 6 months ago (and possibly later; cvsweb sucks).

**Comment by sideshowbarker** [comment]
OK, maybe it’s time to rope in @guibbs on this

**Comment by caribouW3** [comment]
https://github.com/w3c/css-validator  is now the latest version. Closing this issue.
