### ISSUE TITLE
Group dashboard (aka Unitas)

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#59]
Improve design and documentation around
   https://labs.w3.org/unitas/?g=45211

**Comment by tripu** [comment]
Lots of specific ideas [as issues in Unitas](https://github.com/w3c/Unitas/issues).

**Comment by plehegar** [comment]
@tripu, I think we can close this issue and point folks to Unitas for future discussion. ok?

**Comment by plehegar** [comment]
(see also #47 )

**Comment by tripu** [comment]
OK, @plehegar.
