### ISSUE TITLE
Unified Feed

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#60]
The goal of this project is to develop a service that can integrate all of the information being produced as we work (as it happens) and expose it for querying. It is the foundational brick for the dashboard, the notifiers, and possibly other services.

midgard and pheme aren't getting adopted by our systems or groups

**Comment by tripu** [comment]
cf https://w3c.github.io/modern-tooling/#unified-feeds

**Comment by tripu** [comment]
What do you have in mind, @plehegar?
I think it's better to improve the existing tools and push for adoption, instead of starting from scratch.

**Comment by plehegar** [comment]
The issue was appearing in the original modern tooling document and we weren't sure if it got addressed enough. It's not meant to start a new project. If you think we have enough, feel free to point to the existing tools and close the issue.

**Comment by dontcallmedom** [comment]
I think as alluded above, the "problem" is that we have the tools, but I don't think they're getting much adoption - so we should discuss if we feel they are worth advertizing more broadly (which would probably include making sure they're getting the right level of maintenance)

**Comment by plehegar** [comment]
(see also #44 )

**Comment by tripu** [comment]
Taking up @plehegar's suggestion: the closest we got to this is [pheme](https://github.com/w3c/pheme) (and I personally would prefer we recycle that rather than starting a new project; specific bug or feature requests to be filed [against that project](https://github.com/w3c/pheme/issues)).
