### ISSUE TITLE
Group calendar

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/modern-tooling#68]
Provide an easy way for chairs and staff contacts to maintain an on-line calendar of upcoming teleconferences and meetings; that calendar should be available both as an embeddable visual HTML  widget, and as a subscribable icalendar feed.

**Comment by tripu** [comment]
(Related: w3c/Unitas#19)

**Comment by vivienlacourba** [comment]
During the spring W3C AC 2018, AC Reps and AB Members have reiterated that this is an important issue to address to improve communication and participation to working group meetings.

**Comment by plehegar** [comment]
one "cheap" solution would be to use Google calendars and provide a copy of the ical in our servers.

**Comment by plinss** [comment]
FWIW, the TAG and CSSWG have a NextCloud instance with CalDAV and iCal feeds of meeting calendars. No embeddable widget though.

**Comment by plehegar** [comment]
I created https://github.com/w3c/modern-tooling/blob/gh-pages/calendar.md for use cases and requirements and will circulate widely today for feedback/comments.

**Comment by plehegar** [comment]
why should I stay assigned on this one? I thought I had no action beyond drafting the use cases/requirements...

**Comment by plehegar** [comment]
(the md file is a copy of https://docs.google.com/document/d/1tYid63THgA4VNo2AqHtuohmad_Ia9RpjpScJnCj27Sw/edit#heading=h.fnxhawskfpg0 )

**Comment by plehegar** [comment]
(adding @caribouW3 )

**Comment by plehegar** [comment]
note on this front: the group calendaring system is in its final review phase before we deploy it so expect news within 3 weeks.

**Comment by plehegar** [comment]
See
  https://www.w3.org/blog/2021/03/group-calendaring-service-enters-beta-test/

Calendar issues should now go to:
  https://github.com/w3c/calendar
