### ISSUE TITLE
Make TPAC pages more responsive

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#70]
Our TPAC pages need to look good on mobile and work offline.

**Comment by koalie** [comment]
(May we have this issue as part of https://github.com/w3c/design/ instead? (and close it here))

**Comment by plehegar** [comment]
I don't think it's simply a design question. offline mode for one would need to be supported.

**Comment by koalie** [comment]
All right. I'm happy to track w3c/modern-tooling as well!

**Comment by tripu** [comment]
Assigning this issue to myself to keep track of the technical side of these changes. (There's also a political or organisational aspect to it, of which @tguild and others will be taking care.)

**Comment by plehegar** [comment]
It's likely that this idea will get dropped since we're almost in May and haven't done anything.

**Comment by tripu** [comment]
I think these are two separate issues, with different priorities:

* **Make TPAC pages responsive**, highest priority (or else pages aren't usable). We are there, or almost there. Biggest obstacle are large tables, and @bert-github made good progress on those already, altering table headings etc via media queries; cf [`w3.org/2017/11/TPAC`](https://www.w3.org/2017/11/TPAC/) and [`w3.org/2017/11/TPAC/schedule`](https://www.w3.org/2017/11/TPAC/schedule.html).
* **Make them work offline** via Service Workers, lower priority. I should work on this (it's not too late).

**Comment by plehegar** [comment]
The tables aren't really mobile friendly...

**Comment by tripu** [comment]
@plehegar: what table are you looking at, in particular; and what is missing on a narrow screen?

**Comment by koalie** [comment]
Whether @plehegar had that in mind or something else, the fact remains that the TPAC Plenary breakout schedule is a table in a wiki. e.g. [TPAC 2017 session grid](https://www.w3.org/wiki/TPAC/2017#Session_Grid)

**Comment by plehegar** [comment]
I was looking at the "week at a glance" table. The table is too large to fit on a mobile phone, resulting in overlapping text between cells.

**Comment by tripu** [comment]
Note to self: [*&ldquo;Google Developers: Caching Files with Service Worker&rdquo;*](https://developers.google.com/web/ilt/pwa/caching-files-with-service-worker)

**Comment by marcoscaceres** [comment]
Happy to review SW code if you need assistance.

**Comment by tripu** [comment]
@plehegar, some tests of [`w3.org/2017/11/TPAC/#WeekGlance`](https://www.w3.org/2017/11/TPAC/#WeekGlance):

FF Beta 60, Android (1080px width):

![image](https://user-images.githubusercontent.com/1016538/39539168-3d6ab45e-4e3f-11e8-86c7-981e77fa1df7.png)

Chrome Beta 66, Android (1080px width):

![image](https://user-images.githubusercontent.com/1016538/39539246-6d765a18-4e3f-11e8-82e0-ecd5ac7e32a6.png)

Chromium 65, Ubuntu (400px width):

![image](https://user-images.githubusercontent.com/1016538/39539286-80068b76-4e3f-11e8-89fd-8f31ed6bf176.png)

Even down to a width of 400px, the table looks good&hellip; were it not for the bad hyphenation. It seems to me that's the main issue right now.

**Comment by plehegar** [comment]
agreed

**Comment by tripu** [comment]
OK. I'll try to address both issues, then (bad hyphenation, and SW for caching files).

@marcoscaceres, I take your kind offer, and will submit my SW PR for your review.

**Comment by plehegar** [comment]
Abandoned

**Comment by koalie** [comment]
"abandoned"? I beg to differ :) We created a new subsite for TPAC that launched for TPAC 2019 <https://www.w3.org/2019/09/TPAC/> and it's responsive.

I concur however that this issue can be closed.

**Comment by plehegar** [comment]
sorry. I was thinking about PWA when I closed earlier. I didn't encounter issues at the last TPAC so thank you for making the site more responsive!
