### ISSUE TITLE
calendaring: suggestion

### ISSUE THREAD

**Issue by wseltzer** [w3c/modern-tooling#82]
Leonie suggests that we look at the TAG's calendar

**Comment by plinss** [comment]
The TAG uses a NextCloud server for a CalDAV feed, with an automatic export to .ics for a public read-only feed

**Comment by plehegar** [comment]
This seems like information for #68 . ok to close this?

**Comment by plehegar** [comment]
See
  https://www.w3.org/blog/2021/03/group-calendaring-service-enters-beta-test/

Calendar issues should now go to:
  https://github.com/w3c/calendar
