### ISSUE TITLE
Test generation tools

### ISSUE THREAD

**Issue by r12a** [w3c/modern-tooling#9]
Having just gone through the agony of producing large sets of ref tests, which required me to painstakingly edit out content for each ref file copy, check each file separately for validity, ensure that I had all the right (and not too many) components, globally replace certain things across a large number of files, etc., i'd like to see a form-based method of creating tests that would prompt you for the essential information and create the file and markup for you, automatically creating a ref file in a specified directory when needed.

The interface should be able to populate the fields with data from a similar test automatically, to avoid duplicate work. It should also know about resources such as fonts, and enable you to link them in easily as webfonts.  It should also store information such as test author name/contact info, and other repeatable information.

(Btw, it would be my preference to require an assertion, so that others can figure out more easily what the test aims to prove.)

The tool should allow the user to create new test files from scratch, or edit and/or extend an existing set of files.

hth

**Comment by darobin** [comment]
I've added this to the document, thanks!
